### ISSUE TITLE
Apple podcast is not reloaded RSS feed and fetching new episodes (got stuck at episode 1)

### ISSUE THREAD

**Issue by woolfg** [openpodcast/forwarder#6]
manuall update was triggered some days ago but still no update. maybe the forwarded RSS feed is not valid for apple?

![Image](https://user-images.githubusercontent.com/1328269/191014498-5eb55b10-1e9e-4091-af0b-af460bcac5f0.png)

**Comment by mre** [comment]
Deployed a fix and clicked on "refresh RSS". Let's hope for the best. 🤞

**Comment by woolfg** [comment]
no change so far...

**Comment by woolfg** [comment]
solved by @mre by implementation http head request support on forwarder
